(cl:defpackage angen_turtlebot-srv
  (:use )
  (:export
   "SERVICE1_PARAM"
   "<SERVICE1_PARAM-REQUEST>"
   "SERVICE1_PARAM-REQUEST"
   "<SERVICE1_PARAM-RESPONSE>"
   "SERVICE1_PARAM-RESPONSE"
   "SERVICE2_PARAM"
   "<SERVICE2_PARAM-REQUEST>"
   "SERVICE2_PARAM-REQUEST"
   "<SERVICE2_PARAM-RESPONSE>"
   "SERVICE2_PARAM-RESPONSE"
  ))

