/* Auto-generated by genmsg_cpp for file /home/angenuser/ros_workspace/angen_cognitive_environment/angen_turtlebot/msg/navigation_command.msg */
#ifndef ANGEN_TURTLEBOT_MESSAGE_NAVIGATION_COMMAND_H
#define ANGEN_TURTLEBOT_MESSAGE_NAVIGATION_COMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace angen_turtlebot
{
template <class ContainerAllocator>
struct navigation_command_ {
  typedef navigation_command_<ContainerAllocator> Type;

  navigation_command_()
  : location(0)
  , caller()
  {
  }

  navigation_command_(const ContainerAllocator& _alloc)
  : location(0)
  , caller(_alloc)
  {
  }

  typedef uint8_t _location_type;
  uint8_t location;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _caller_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  caller;


  typedef boost::shared_ptr< ::angen_turtlebot::navigation_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::angen_turtlebot::navigation_command_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct navigation_command
typedef  ::angen_turtlebot::navigation_command_<std::allocator<void> > navigation_command;

typedef boost::shared_ptr< ::angen_turtlebot::navigation_command> navigation_commandPtr;
typedef boost::shared_ptr< ::angen_turtlebot::navigation_command const> navigation_commandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::angen_turtlebot::navigation_command_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::angen_turtlebot::navigation_command_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace angen_turtlebot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::angen_turtlebot::navigation_command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::angen_turtlebot::navigation_command_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::angen_turtlebot::navigation_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "87e245bd936b9d0853e860f013c1a5fa";
  }

  static const char* value(const  ::angen_turtlebot::navigation_command_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x87e245bd936b9d08ULL;
  static const uint64_t static_value2 = 0x53e860f013c1a5faULL;
};

template<class ContainerAllocator>
struct DataType< ::angen_turtlebot::navigation_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "angen_turtlebot/navigation_command";
  }

  static const char* value(const  ::angen_turtlebot::navigation_command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::angen_turtlebot::navigation_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 location\n\
string caller\n\
\n\
";
  }

  static const char* value(const  ::angen_turtlebot::navigation_command_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::angen_turtlebot::navigation_command_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.location);
    stream.next(m.caller);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct navigation_command_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::angen_turtlebot::navigation_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::angen_turtlebot::navigation_command_<ContainerAllocator> & v) 
  {
    s << indent << "location: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.location);
    s << indent << "caller: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.caller);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ANGEN_TURTLEBOT_MESSAGE_NAVIGATION_COMMAND_H

