(cl:defpackage angen_apps-srv
  (:use )
  (:export
   "ANGENACTUATORSSTATUS"
   "<ANGENACTUATORSSTATUS-REQUEST>"
   "ANGENACTUATORSSTATUS-REQUEST"
   "<ANGENACTUATORSSTATUS-RESPONSE>"
   "ANGENACTUATORSSTATUS-RESPONSE"
  ))

